# nodeci.yml
# deploy to aliyun ecs
name: deploy to aliyun ecs
on:
  push:
    branches:
      - master
jobs:
  # build production
  build:
    runs-on: ubuntu-latest
    steps:
      #pre setup
      - name: Checkout
        uses: actions/checkout@master
      - name: use nodejs 12
        uses: actions/setup-node@v1
        with:
              node-version: '12'
      #npm install and build
      - run: npm install
      - run: npm run build
  #deploy production
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: deploy
          uses: easingthemes/ssh-deploy@v2.1.5
          env:
            SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
            ARGS: "-rltgoDzvO"
            SOURCE: "dist/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}